version: '3.8'

services:
  vue-app:
    image: node:latest
    container_name: vue_deb
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # Evita problemas de node_modules en volumen
    ports:
      - "5174:5173"
    command: sh -c "npm install && npm run dev -- --host"
